[package]
name = "patsh"
version = "0.1.2"
authors = ["figsoda <figsoda@pm.me>"]
edition = "2021"
description = "A command-line tool for patching shell scripts"
readme = "README.md"
homepage = "https://github.com/nix-community/patsh"
repository = "https://github.com/nix-community/patsh"
license = "MPL-2.0"
keywords = ["bash", "cli", "nix", "patch", "shell"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.66"
expand = "0.2.1"
tree-sitter = "0.20.9"
which = "4.3.0"

[dependencies.clap]
version = "4.0.27"
features = ["cargo", "derive", "unicode", "wrap_help"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
